const $=s=>document.querySelector(s),tabs=[...document.querySelectorAll('[role="tab"]')],panels=[...document.querySelectorAll('[role="tabpanel"]')];
let data=null,editing=null,subtracting=null,busy=false;
const grams=n=>`${Number(n).toLocaleString(undefined,{maximumFractionDigits:1})} g`,money=n=>new Intl.NumberFormat(undefined,{style:'currency',currency:'USD'}).format(Number(n)||0);
function status(t,tone='neutral'){let e=$('#status');e.textContent=t;e.dataset.tone=tone}
function tab(name,focus=false){tabs.forEach(x=>{let a=x.dataset.tab===name;x.classList.toggle('active',a);x.setAttribute('aria-selected',a);x.tabIndex=a?0:-1;if(a&&focus)x.focus()});panels.forEach(x=>x.hidden=x.id!==`${name}-panel`);let x=tabs.find(x=>x.dataset.tab===name);$('#pageTitle').textContent=x?.dataset.title||'Workspace'}
function value(r){let s=Number(r.startingFilamentWeightG),c=Number(r.currentFilamentWeightG),p=Number(r.purchaseCost);return s>0&&Number.isFinite(c)&&Number.isFinite(p)?p*c/s:0}
function referenced(id){return data.projects.some(p=>Array.isArray(p.filamentUsage)&&p.filamentUsage.some(u=>u.filamentId===id))}
function visible(){let q=$('#searchRolls').value.trim().toLowerCase(),f=$('#statusFilter').value,low=$('#lowStockOnly').checked,limit=Number(data.settings.lowStockThresholdG)||0;return data.filaments.filter(r=>{if(f==='active'&&r.archived)return false;if(f==='archived'&&!r.archived)return false;if(low&&Number(r.currentFilamentWeightG)>=limit)return false;return !q||[r.rollCode,r.brand,r.material,r.colorName,r.binLocation].some(v=>String(v||'').toLowerCase().includes(q))}).sort((a,b)=>Number(a.archived)-Number(b.archived)||a.colorName.localeCompare(b.colorName))}
function render(){if(!data)return;let active=data.filaments.filter(r=>!r.archived),limit=Number(data.settings.lowStockThresholdG)||0,low=active.filter(r=>Number(r.currentFilamentWeightG)<limit),weight=active.reduce((s,r)=>s+Number(r.currentFilamentWeightG||0),0),total=active.reduce((s,r)=>s+value(r),0);$('#activeRollCount').textContent=active.length;$('#lowStockCount').textContent=low.length;$('#lowStockLabel').textContent=`Below ${grams(limit)}`;$('#lowStockFilterText').textContent=`Under ${grams(limit)}`;$('#totalWeight').textContent=grams(weight);$('#remainingValue').textContent=money(total);let rolls=visible();$('#inventoryList').innerHTML=rolls.map(r=>`<article class="roll-card" data-id="${r.id}" data-archived="${r.archived}"><div class="roll-heading"><input class="roll-swatch" type="color" value="${r.colorHex}" disabled><div class="roll-identity"><h3>${esc(r.colorName)}</h3><p>${esc(r.rollCode)}</p></div><div class="roll-badges"><span>${esc(r.brand)}</span><span>${esc(r.material)}</span>${!r.archived&&Number(r.currentFilamentWeightG)<limit?'<span class="warning-chip">Low stock</span>':''}${r.archived?'<span class="archived-chip">Archived</span>':''}</div></div><dl class="roll-details"><div><dt>Remaining</dt><dd>${grams(r.currentFilamentWeightG)}</dd></div><div><dt>Starting</dt><dd>${grams(r.startingFilamentWeightG)}</dd></div><div><dt>Location</dt><dd>${esc(r.binLocation||'Not assigned')}</dd></div><div><dt>Purchase cost</dt><dd>${money(r.purchaseCost)}</dd></div><div><dt>Remaining value</dt><dd>${money(value(r))}</dd></div><div><dt>Stock TD</dt><dd>${r.tdStock==null?'Not entered':Number(r.tdStock).toFixed(2)+' mm'}</dd></div></dl><div class="roll-actions"><button data-act="edit">Edit</button><button data-act="subtract" ${r.archived||Number(r.currentFilamentWeightG)<=0?'disabled':''}>Subtract weight</button><button data-act="archive">${r.archived?'Restore':'Archive'}</button><button data-act="delete" class="danger">Delete</button></div></article>`).join('');let none=!rolls.length,has=data.filaments.length>0;$('#inventoryEmpty').hidden=!none;$('#inventoryEmpty b').textContent=has?'No rolls match these filters':'No rolls yet';$('#inventoryEmpty p').textContent=has?'Clear the search or change the filters.':'Add your first physical filament roll to begin building Roll Brain.';$('#addFirstRoll').hidden=has}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function formError(t=''){let e=$('#rollFormError');e.textContent=t;e.hidden=!t}
function openRoll(id=null){let r=id?data.filaments.find(x=>x.id===id):null;editing=r?.id||null;$('#rollDialogTitle').textContent=r?`Edit ${r.colorName}`:'Add filament roll';$('#saveRoll').textContent=r?'Save changes':'Add roll';let set=(id,v)=>$(id).value=v??'';set('#rollCode',r?.rollCode);set('#brand',r?.brand);set('#material',r?.material||'PLA');set('#colorName',r?.colorName);set('#colorHex',r?.colorHex||'#7c5cff');set('#startingWeight',r?.startingFilamentWeightG??1000);set('#currentWeight',r?.currentFilamentWeightG??1000);set('#spoolTare',r?.spoolTareWeightG);set('#purchaseCost',r?.purchaseCost??0);set('#purchaseDate',r?.purchaseDate);set('#binLocation',r?.binLocation);set('#tdStock',r?.tdStock);set('#rollNotes',r?.notes);formError();$('#rollDialog').showModal();$('#rollCode').focus()}
function closeRoll(){editing=null;$('#rollDialog').close()}
function build(){let old=editing?data.filaments.find(r=>r.id===editing):null,num=id=>$(id).value===''?null:Number($(id).value),now=new Date().toISOString(),r={id:old?.id||crypto.randomUUID(),rollCode:$('#rollCode').value.trim(),brand:$('#brand').value.trim(),material:$('#material').value.trim(),colorName:$('#colorName').value.trim(),colorHex:$('#colorHex').value,startingFilamentWeightG:num('#startingWeight'),currentFilamentWeightG:num('#currentWeight'),spoolTareWeightG:num('#spoolTare'),purchaseCost:num('#purchaseCost')??0,purchaseDate:$('#purchaseDate').value||null,binLocation:$('#binLocation').value.trim(),tdStock:num('#tdStock'),tdMeasured:old?.tdMeasured??null,tdMeasuredDate:old?.tdMeasuredDate??null,swatchPhotoPath:old?.swatchPhotoPath??null,notes:$('#rollNotes').value.trim(),archived:old?.archived??false,createdAt:old?.createdAt||now,updatedAt:now};if(!r.rollCode||!r.brand||!r.material||!r.colorName)throw Error('Roll code, brand, material, and color name are required.');if(!(r.startingFilamentWeightG>0)||r.currentFilamentWeightG<0)throw Error('Enter valid non-negative filament weights.');if(r.currentFilamentWeightG>r.startingFilamentWeightG)throw Error('Current filament weight cannot exceed starting weight.');if(data.filaments.some(x=>x.id!==r.id&&x.rollCode.toLowerCase()===r.rollCode.toLowerCase()))throw Error(`Roll code ${r.rollCode} is already in use.`);return r}
async function commit(next,msg){if(busy)return false;busy=true;status('Saving and verifying inventory...','working');try{let res=await window.layerWorks.saveData(next);if(!res?.ok||!res.data)throw Error('The save was not confirmed.');data=res.data;$('#dataPath').textContent=res.path;render();status(`${msg} · ${new Date(res.savedAt).toLocaleTimeString()}`,'success');return true}catch(e){console.error(e);status(`Save failed: ${e.message}`,'error');return false}finally{busy=false}}
async function saveRoll(e){e.preventDefault();try{let r=build(),next=structuredClone(data),i=next.filaments.findIndex(x=>x.id===r.id);i<0?next.filaments.push(r):next.filaments[i]=r;if(await commit(next,i<0?'Roll added':'Roll updated'))closeRoll()}catch(e){formError(e.message)}}
function openSubtract(id){let r=data.filaments.find(x=>x.id===id);if(!r||r.archived)return;subtracting=id;$('#subtractRollName').textContent=`${r.colorName} · ${r.rollCode} has ${grams(r.currentFilamentWeightG)} remaining.`;$('#subtractAmount').value='';$('#subtractAmount').max=r.currentFilamentWeightG;$('#subtractRemaining').textContent=`New remaining weight: ${grams(r.currentFilamentWeightG)}`;$('#subtractError').hidden=true;$('#subtractDialog').showModal();$('#subtractAmount').focus()}
function closeSubtract(){subtracting=null;$('#subtractDialog').close()}
async function subtract(e){e.preventDefault();let r=data.filaments.find(x=>x.id===subtracting),n=Number($('#subtractAmount').value),err=$('#subtractError');if(!r)return;if(!(n>0)||n>Number(r.currentFilamentWeightG)){err.textContent=n>Number(r.currentFilamentWeightG)?`Cannot subtract ${grams(n)}; only ${grams(r.currentFilamentWeightG)} remains.`:'Enter a positive number of grams.';err.hidden=false;return}let next=structuredClone(data),x=next.filaments.find(x=>x.id===r.id);x.currentFilamentWeightG=Number((x.currentFilamentWeightG-n).toFixed(3));x.updatedAt=new Date().toISOString();if(await commit(next,`${grams(n)} subtracted`))closeSubtract()}
async function cardAction(e){let b=e.target.closest('button[data-act]'),card=e.target.closest('.roll-card');if(!b||!card)return;let id=card.dataset.id,r=data.filaments.find(x=>x.id===id);if(b.dataset.act==='edit')openRoll(id);if(b.dataset.act==='subtract')openSubtract(id);if(b.dataset.act==='archive'&&confirm(`${r.archived?'Restore':'Archive'} ${r.colorName}?`)){let next=structuredClone(data),x=next.filaments.find(x=>x.id===id);x.archived=!x.archived;x.updatedAt=new Date().toISOString();await commit(next,x.archived?'Roll archived':'Roll restored')}if(b.dataset.act==='delete'){if(referenced(id)){alert('This roll is referenced by a project and must be archived instead.');return}if(confirm(`Permanently delete ${r.colorName} (${r.rollCode})?`)){let next=structuredClone(data);next.filaments=next.filaments.filter(x=>x.id!==id);await commit(next,'Roll permanently deleted')}}}
function disable(msg){['#addRoll','#addRollHero','#addFirstRoll','#searchRolls','#statusFilter','#lowStockOnly'].forEach(s=>$(s).disabled=true);$('#inventoryNotice').hidden=false;$('#inventoryNotice').textContent=msg;$('#inventoryEmpty').hidden=true}
async function load(){try{let [res,path]=await Promise.all([window.layerWorks.loadData(),window.layerWorks.dataPath()]);if(!res?.ok||!res.data)throw Error(res?.error||'Local data could not be loaded.');data=res.data;$('#dataPath').textContent=res.path||path;render();status(res.created?'Local inventory file created':'Local inventory loaded','success')}catch(e){console.error(e);status('Inventory could not be loaded','error');disable(e.message)}}
tabs.forEach((x,i)=>{x.onclick=()=>tab(x.dataset.tab);x.onkeydown=e=>{if(!['ArrowDown','ArrowUp','Home','End'].includes(e.key))return;e.preventDefault();let n=e.key==='Home'?0:e.key==='End'?tabs.length-1:e.key==='ArrowDown'?(i+1)%tabs.length:(i-1+tabs.length)%tabs.length;tab(tabs[n].dataset.tab,true)}});['#addRoll','#addRollHero','#addFirstRoll'].forEach(s=>$(s).onclick=()=>openRoll());$('#closeRollDialog').onclick=$('#cancelRoll').onclick=closeRoll;$('#rollForm').onsubmit=saveRoll;$('#closeSubtractDialog').onclick=$('#cancelSubtract').onclick=closeSubtract;$('#subtractForm').onsubmit=subtract;$('#subtractAmount').oninput=()=>{let r=data?.filaments.find(x=>x.id===subtracting),n=Number($('#subtractAmount').value||0);if(r)$('#subtractRemaining').textContent=n>r.currentFilamentWeightG?`This exceeds ${grams(r.currentFilamentWeightG)}.`:`New remaining weight: ${grams(r.currentFilamentWeightG-n)}`};['#searchRolls','#statusFilter','#lowStockOnly'].forEach(s=>$(s).addEventListener(s==='#searchRolls'?'input':'change',render));$('#inventoryList').onclick=cardAction;$('#rollDialog').onclick=e=>{if(e.target===$('#rollDialog'))closeRoll()};$('#subtractDialog').onclick=e=>{if(e.target===$('#subtractDialog'))closeSubtract()};$('#appName').textContent=window.layerWorks?.appName||"Love's LayerWorks Hub";$('#milestone').textContent=window.layerWorks?.milestone||'M1A';tab('inventory');load();
